// Generated by CoffeeScript 1.10.0
(function() {
  exports.queue = function(callbacks, defaultScope) {
    var index, self;
    index = 0;
    if (!(callbacks instanceof Array)) {
      callbacks = [].slice.call(arguments);
    }
    self = function() {
      var fn;
      fn = callbacks[index++];
      return fn && fn.call(defaultScope, self);
    };
    return self();
  };

}).call(this);

//# sourceMappingURL=util.js.map
