// Generated by CoffeeScript 1.10.0
(function() {
  var buy, configureRequest, getNonce, info, key, nonce, parseBody, querystring, request, secret, sell, send, sha, ticker, trade, url;

  request = require('request');

  querystring = require('querystring');

  sha = require('crypto-js/hmac-sha512');

  key = '09B5K4AX-PWF0M87C-EVAXIO8S-1E9BNZHZ-EFVWYUYY';

  secret = '517b8dbf6af2783ad4e4e8aeb19af368a590d2c41987d49f74ccf23006caebd5';

  url = 'https://btc-e.nz/tapi';

  nonce = 0;

  info = function() {
    log('[BTCE] Запрос тикера');
    return send({
      opt: {
        method: 'getInfo'
      }
    });
  };

  buy = function(opt) {
    log("[BTCE] Выставление на продажу " + (JSON.stringify(opt)));
    opt.type = 'buy';
    return trade(opt);
  };

  sell = function(opt) {
    log("[BTCE] Выставление на покупку " + (JSON.stringify(opt)));
    opt.type = 'sell';
    return trade(opt);
  };

  ticker = function(pair) {
    return send({
      url: "https://btc-e.nz/api/2/" + pair + "/ticker",
      method: 'GET'
    });
  };

  module.exports = {
    info: info,
    buy: buy,
    sell: sell,
    ticker: ticker
  };

  trade = function(opt) {
    opt.method = 'Trade';
    return send({
      opt: opt
    });
  };

  send = function(config) {
    return configureRequest(config, function(params) {
      var target;
      target = config.url || url;
      return request(target, params, function(error, response, body) {
        var failure;
        body = parseBody(body);
        failure = error || body.success === 0;
        if (failure) {
          logError('[E][BTCE] Проблемы с драйвером', error, body);
          if (typeof config.failure === "function") {
            config.failure(error, body);
          }
        } else {
          log("[BTCE] Тело результата: " + ((function() {
            try {
              return JSON.stringify(body);
            } catch (undefined) {}
          })()));
          if (typeof config.success === "function") {
            config.success(body);
          }
        }
        return typeof config.always === "function" ? config.always(error, body) : void 0;
      });
    });
  };

  configureRequest = function(config, next) {
    return getNonce(config, function(nonce) {
      var opt, query;
      opt = config.opt || {};
      opt.param = 0;
      opt.value = 0;
      opt.nonce = nonce;
      query = querystring.stringify(opt);
      return next({
        method: config.method || 'POST',
        form: opt,
        headers: {
          key: key,
          sign: sha(query, secret)
        }
      });
    });
  };

  getNonce = function(config, next) {
    if (config.url) {
      next;
    }
    if (nonce) {
      next(++nonce);
    }
    nonce = 11;
    return next(nonce);
  };

  parseBody = function(body) {
    var error1;
    try {
      return JSON.parse(body);
    } catch (error1) {
      return {
        success: 0,
        robotDriverError: 'Can not parse body'
      };
    }
  };

}).call(this);

//# sourceMappingURL=BTCE.js.map
