// Generated by CoffeeScript 1.10.0
(function() {
  var action, btc, buy, getAccountState, getPairState, lastBuy, lastSell, name, pair, sell, tickTime, trade, trader, usd;

  pair = 'btc_usd';

  name = "[BTCE " + pair + "]";

  trader = require('./trader');

  tickTime = 3000;

  buy = 0;

  sell = 0;

  lastBuy = 0;

  lastSell = 0;

  usd = 0;

  btc = 0;

  trade = function() {
    return getAccountState(function() {
      return getPairState(function() {
        return action();
      });
    });
  };

  getAccountState = function(next) {
    return trader.info({
      success: function(value) {
        var error, funds;
        try {
          funds = value["return"].funds;
          usd = funds.usd;
          btc = funds.btc;
          return next();
        } catch (error) {
          return logError(name + " Ошибка формата состояния аккаунта");
        }
      },
      failure: function() {
        return logError(name + " Ошибка получения текущей информации");
      }
    });
  };

  getPairState = function(next) {
    return trader.ticker({
      pair: pair,
      success: function(value) {
        var error, ticker;
        try {
          ticker = value.ticker;
          lastBuy = buy;
          lastSell = sell;
          buy = ticker.buy;
          sell = ticker.sell;
          return next();
        } catch (error) {
          return logError(name + " Ошибка формата тикера");
        }
      }
    });
  };

  action = function() {
    var buyAmount;
    if (!lastSell) {
      return;
    }
    if (btc && sell < lastSell) {
      trader.sell({
        pair: pair,
        rate: +((sell * 1.00001).toFixed(3)),
        amount: btc
      });
      return;
    }
    buyAmount = +(((usd / sell) - 0.001).toFixed(5));
    if (buyAmount && usd && buy > lastBuy) {
      trader.buy({
        pair: pair,
        rate: sell,
        amount: buyAmount
      });
    }
  };

  trade();

  setInterval(trade, tickTime);

}).call(this);

//# sourceMappingURL=btc_usd.js.map
